/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthInsurance.ClaimsOrganization;

import Business.EcoSystem;
import Business.Enterprise.DepartmentOfPublicHealthEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HealthInsuranceEnterprise;
import Business.Network.Network;
import Business.Organization.DepartmentOfPublicHealth.DivisionOfInsurance;
import Business.Organization.HealthInsurance.ClaimsOrganization;
import Business.Organization.Hospital.ReleaseOfInfoOrganization;
import Business.Organization.Organization;
import Business.ReimbursementDirectory;
import Business.UserAccount.UserAccount;
//import Business.WorkQueue.Claim_DepartmentWorkRequest;
import Business.WorkQueue.Claim_DeptHealthInsuranceWorkRequest;
import userinterface.DepartmentOfPublicHealth.AdulterationOfficer.*;
import Business.WorkQueue.ComplainWorkRequest;
import Business.WorkQueue.ROI_ClaimWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.Hospital.Releaseinfo.ClaimStatusJPanel;

/**
 *
 * @author mitka
 */
public class ProcessClaimsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessFraudComplainJPanel
     */
    JPanel userProcessContainer;
    //ComplainWorkRequest request;
    ROI_ClaimWorkRequest request;
   EcoSystem business;
   private UserAccount userAccount;
   private Organization org;
   private ClaimsOrganization claimorg;
   private DivisionOfInsurance DivInsOrg;
    public ProcessClaimsJPanel(JPanel userProcessContainer, Organization organization, UserAccount userAccount, Enterprise enterprise ,EcoSystem Business)  {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
       this.business = new EcoSystem();
        this.business = Business;
        this.userAccount = userAccount;
        this.claimorg = (ClaimsOrganization)organization;
        populatecombo();
    }

    public void populatecombo()
    {
    governmentOrgComboBox.removeAllItems();
        for(Network network: business.getNetworkList())
        {
            for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){ 
                if (e instanceof DepartmentOfPublicHealthEnterprise)
               for(Organization org1:e.getOrganizationDirectory().getOrganizationList()){
                      governmentOrgComboBox.addItem(org1);
                    }
                }
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        resultTextField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        RequestJBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        governmentOrgComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Message ");

        resultTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTextFieldActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        RequestJBtn.setText("Raise Request");
        RequestJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestJBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Receiving Organization:");

        governmentOrgComboBox.setToolTipText("");
        governmentOrgComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                governmentOrgComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(governmentOrgComboBox, 0, 416, Short.MAX_VALUE)
                            .addComponent(resultTextField))
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RequestJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(governmentOrgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 431, Short.MAX_VALUE)
                .addComponent(RequestJBtn)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ClaimsOfficerWorkAreaJPanel dwjp = (ClaimsOfficerWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void RequestJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestJBtnActionPerformed
        // TODO add your handling code here:
         Claim_DeptHealthInsuranceWorkRequest req = new Claim_DeptHealthInsuranceWorkRequest();
         req.setMessage("Verify the Medical Claim");
//         req.setOrganizationName(org.getName());
         req.setStatus("Sent");
         req.setSender(userAccount);
         req.setStatus("Under Verification");
         req.setFraudDetected("Claim will be provided once verification is done");
         
         Organization org = null;
         for(Network network: business.getNetworkList()){
             System.out.println("network = "+network.getName());
            for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof DepartmentOfPublicHealthEnterprise){
                    for(Organization loopOrg:e.getOrganizationDirectory().getOrganizationList()){
                        if(governmentOrgComboBox.getSelectedItem().toString().equals(loopOrg.getName())){
                            org = loopOrg;
                            break;
                    }
                }
            }
        }
         }
         if(org!=null){
            org.getWorkQueue().getWorkRequestList().add(req);
            claimorg.getWorkQueue().getWorkRequestList().add(req);
         }
         JOptionPane.showMessageDialog(null,"Request send to Department of Health Insurance !!");
        
 
    }//GEN-LAST:event_RequestJBtnActionPerformed

    private void governmentOrgComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_governmentOrgComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_governmentOrgComboBoxActionPerformed

    private void resultTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestJBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox governmentOrgComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField resultTextField;
    // End of variables declaration//GEN-END:variables
}
