/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthInsurance.ClaimsOrganization;

//import userinterface.Hospital.Patient.*;
import Business.EcoSystem;
import Business.Enterprise.DepartmentOfPublicHealthEnterprise;
import java.awt.CardLayout;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.DepartmentOfPublicHealth.*;
import javax.swing.JPanel;
import Business.UserAccount.UserAccount;
import Business.Organization.Hospital.PatientOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.ComplainWorkRequest;
import Business.WorkQueue.Insurnce_PatientWorkRequest;
import Business.WorkQueue.ROI_ClaimWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.Component;

/**
 *
 * @author Samartha
 */
public class RequestPatientReport extends javax.swing.JPanel {
  private JPanel userProcessContainer;
  private Enterprise enterprise;
  private UserAccount userAccount;
  private PatientOrganization patient;
  private EcoSystem business;
  private String patient_InsuranceID;
  private ROI_ClaimWorkRequest wr1;
  private String PatientInsuranceId;
  private String PatientMedicalID;
  private String patientID;
    /**
     * Creates new form Lodge_complaint
     */
    public RequestPatientReport(JPanel userProcessContainer, UserAccount account, PatientOrganization patient, Enterprise enterprise, EcoSystem business ,String patientID,String PatientMedicalID) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.PatientMedicalID = PatientMedicalID;
        this.patientID = patientID;
        valueLabel.setText(enterprise.getName());
        
     populate_Combo();
     populate_text();
        
    }
    
    public void populate_text()
    {
    PatientTxt.setText(PatientMedicalID);
    PatientTxt.setEnabled(false);
    }
    public void populate_Combo()
    {
//        governmentOrgComboBox.removeAll();
//        EntCoboBox.removeAll();
//        
//        for(Network network: business.getNetworkList()){
//          for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){ 
//              EntCoboBox.addItem(e);
//              if(e instanceof DepartmentOfPublicHealthEnterprise){
//                    for(Organization org:e.getOrganizationDirectory().getOrganizationList()){
//                        governmentOrgComboBox.addItem(org);
//                    }
//                }
//               if(e instanceof HospitalEnterprise){
//                   EntCoboBox.addItem(e);
//                  for(Organization org:e.getOrganizationDirectory().getOrganizationList()){
//                      governmentOrgComboBox.addItem(org);
//                    }
//                }
//          }  
//        }
        
        governmentOrgComboBox.removeAll();
       EntCoboBox.removeAll();

       for(Network network: business.getNetworkList()){
         for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
             if(e instanceof HospitalEnterprise){
                 EntCoboBox.addItem(e);

             for(Organization looporg:e.getOrganizationDirectory().getOrganizationList()){
                 if(looporg instanceof PatientOrganization){
                     governmentOrgComboBox.addItem(looporg);
                 }
             }
             }
           }
        
        
       }

        
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SendRequestPatient = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MessageLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageTxt = new javax.swing.JTextArea();
        EntrpriseComboBox = new javax.swing.JLabel();
        EntCoboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        governmentOrgComboBox = new javax.swing.JComboBox();
        PatientTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(210, 247, 247));

        SendRequestPatient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SendRequestPatient.setText("Send Request");
        SendRequestPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendRequestPatientActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<value>");

        MessageLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        MessageLbl.setText("Message");

        MessageTxt.setColumns(20);
        MessageTxt.setRows(5);
        jScrollPane1.setViewportView(MessageTxt);

        EntrpriseComboBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EntrpriseComboBox.setText("Enterprise");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Receiving Organization:");

        governmentOrgComboBox.setToolTipText("");
        governmentOrgComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                governmentOrgComboBoxActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Patient Medical ID");

        jTextField1.setBackground(new java.awt.Color(210, 247, 247));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("REQUEST PATIENT FOR  CLAIMS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MessageLbl)
                            .addComponent(jLabel3)
                            .addComponent(EntrpriseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(948, 948, 948))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EntCoboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(governmentOrgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(SendRequestPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(MessageLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(EntrpriseComboBox)
                .addGap(1, 1, 1)
                .addComponent(EntCoboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(governmentOrgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(SendRequestPatient)
                .addGap(27, 27, 27)
                .addComponent(backBtn)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SendRequestPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendRequestPatientActionPerformed
        boolean flag = false;         
         ComplainWorkRequest ComplainWorkRequest = new ComplainWorkRequest(); 
         ComplainWorkRequest.setPatientID(patientID);
         ComplainWorkRequest.setMessage(MessageTxt.getText());
         ComplainWorkRequest.setStatus("Sent");
         ComplainWorkRequest.setSender(userAccount);
         ComplainWorkRequest.setReceiver(userAccount);

        ComplainWorkRequest.setpatientMedical(PatientMedicalID);
         
        Organization org = null;
        for(Network network: business.getNetworkList()){
            for(Enterprise ent:network.getEnterpriseDirectory().getEnterpriseList()){
               if (ent instanceof HospitalEnterprise){
                     for(Organization loopOrg:ent.getOrganizationDirectory().getOrganizationList()){
                        if(governmentOrgComboBox.getSelectedItem().toString() == loopOrg.getName()){
                            org = loopOrg;
                            flag = true;
                            break;
                        }
                    }  
               }
            }
        } 
         if(org!=null)
         {
            org.getWorkQueue().getComplainWorkRequestList().add(ComplainWorkRequest);
            userAccount.getWorkQueue().getComplainWorkRequestList().add(ComplainWorkRequest);
         }
          
        CheckPatientReportStatus CheckPatientReportStatus = new CheckPatientReportStatus(userProcessContainer,userAccount,enterprise);
        userProcessContainer.add("CheckPatientReportStatus", CheckPatientReportStatus);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_SendRequestPatientActionPerformed

    private void governmentOrgComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_governmentOrgComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_governmentOrgComboBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        SendRequestPatient.setEnabled(false);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EntCoboBox;
    private javax.swing.JLabel EntrpriseComboBox;
    private javax.swing.JLabel MessageLbl;
    private javax.swing.JTextArea MessageTxt;
    private javax.swing.JTextField PatientTxt;
    private javax.swing.JButton SendRequestPatient;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JComboBox governmentOrgComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

   
}
