/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.Patient;

import Business.EcoSystem;
import Business.Enterprise.DepartmentOfPublicHealthEnterprise;
import java.awt.CardLayout;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DepartmentOfPublicHealth.*;
import javax.swing.JPanel;
import Business.UserAccount.UserAccount;
import Business.Organization.Hospital.PatientOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.ComplainWorkRequest;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Samartha
 */
public class LodgeComplainJPanel extends javax.swing.JPanel {
  private JPanel userProcessContainer;
  private Enterprise enterprise;
  private UserAccount userAccount;
  private PatientOrganization patient;
  private ComplainWorkRequest request;
  private EcoSystem business;
  private ItemHandler handler;
  private static int count = 1; 
    /**
     * Creates new form Lodge_complaint
     */
    public LodgeComplainJPanel(JPanel userProcessContainer, UserAccount account, PatientOrganization patient, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        valueLabel.setText(enterprise.getName());
        patientNameTextField.setText(account.getEmployee().getName());
 
        request = new ComplainWorkRequest();
        handler =new ItemHandler();
        complainIdTextField.setText("COM"+count);
             
        complainTypeComboBox.removeAllItems();
        //complainTypeComboBox.addItem(ComplainWorkRequest.ComplainType.InsuranceFraud.getValue());
        complainTypeComboBox.addItem(ComplainWorkRequest.ComplainType.MedicineFraud.getValue());
        complainTypeComboBox.addItem(ComplainWorkRequest.ComplainType.MedicalServFraud.getValue());
        complainTypeComboBox.addItemListener(handler);
        
        governmentOrgComboBox.removeAllItems();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lodgeComplainBtn = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        complainDescTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        governmentOrgComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        complainTypeComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        pdfLabel = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        complainIdTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(210, 247, 247));

        lodgeComplainBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lodgeComplainBtn.setText("Lodge Complaint");
        lodgeComplainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lodgeComplainBtnActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        enterpriseLabel.setText("Enterprise :");

        valueLabel.setText("<value>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Patient Name:");

        patientNameTextField.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Complain Description:");

        complainDescTextArea.setColumns(20);
        complainDescTextArea.setRows(5);
        jScrollPane1.setViewportView(complainDescTextArea);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Receiving Organization:");

        governmentOrgComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Complain Type:");

        complainTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        complainTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Upload Document:");

        pdfLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        uploadButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Complain ID:");

        complainIdTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(governmentOrgComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patientNameTextField)
                            .addComponent(complainTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pdfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lodgeComplainBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(complainIdTextField))
                        .addGap(27, 27, 27)
                        .addComponent(uploadButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(backButton)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(patientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(complainIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(complainTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(governmentOrgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pdfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(uploadButton))
                .addGap(54, 54, 54)
                .addComponent(lodgeComplainBtn)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lodgeComplainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lodgeComplainBtnActionPerformed
  
        if((pdfLabel.getText().isEmpty())||(complainDescTextArea.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Please enter all input fields");
        }
        else{
            request.setMessage(complainDescTextArea.getText());
            request.setEnterpriseName(enterprise.getName());
            //request.setEnterpriseId(enterprise.getOrganizationId());
            request.setStatus("Sent");
            request.setSender(userAccount);
            request.setPatientID("COM"+count);
            System.out.println("count = "+count);
            count++; 
            
            Organization org = null;
         
            for(Network network: business.getNetworkList()){
                for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                    if(e instanceof DepartmentOfPublicHealthEnterprise){
                        for(Organization loopOrg:e.getOrganizationDirectory().getOrganizationList()){
                            if(governmentOrgComboBox.getSelectedItem().toString() == loopOrg.getName()){
                                org = loopOrg;
                                break;
                            }
                            else if(governmentOrgComboBox.getSelectedItem().toString() == loopOrg.getName()){
                                org = loopOrg;
                                break;
                            }
                            else if(governmentOrgComboBox.getSelectedItem().toString() == loopOrg.getName()){
                                org = loopOrg;
                                break;
                            
                            }
                        
                        }
                    }
                }
            }
            if(org!=null){
                
                org.getWorkQueue().getComplainWorkRequestList().add(request);
                userAccount.getWorkQueue().getComplainWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "Your complain has been sent");
                request.setPatientstatusDoc("File sent");

                
                
//                if(userAccount.getWorkQueue().getComplainWorkRequestList().isEmpty()){
//                    org.getWorkQueue().getComplainWorkRequestList().add(request);
//                    userAccount.getWorkQueue().getComplainWorkRequestList().add(request);
//                    JOptionPane.showMessageDialog(null, "Your complain has been sent");
//                    request.setPatientstatusDoc("File sent to government");
//                    System.out.println("in loop:"+userAccount.getWorkQueue().getComplainWorkRequestList().size());
//                }
//                else{
//                for(ComplainWorkRequest req:userAccount.getWorkQueue().getComplainWorkRequestList()){
//                    System.out.println(req.getPatientID());
//                    System.out.println(request.getPatientID());
//                    if(request.getPatientID().equals(req.getPatientID())){
//                    
//                        JOptionPane.showMessageDialog(null, "Your complain already exist");
//                    }
//                    else{
//                        org.getWorkQueue().getComplainWorkRequestList().add(request);
//                        userAccount.getWorkQueue().getComplainWorkRequestList().add(request);
//                        JOptionPane.showMessageDialog(null, "Your complain has been sent");
//                        request.setPatientstatusDoc("File sent to government");
//                        System.out.println("in else loop:"+userAccount.getWorkQueue().getComplainWorkRequestList().size());
//                    }
//                
//                }
//                
//            }
            }
            
        }  

        
        
//        ComplainStatusJPanel complainstatusJPanel = new ComplainStatusJPanel(userProcessContainer,userAccount,enterprise,patient,business);
//        userProcessContainer.add("ComplainStatusJpanel", complainstatusJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);

    }//GEN-LAST:event_lodgeComplainBtnActionPerformed

    private void complainTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complainTypeComboBoxActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF files","pdf");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            request.setPath(selectedFile.getAbsolutePath());
            pdfLabel.setText("File Uploaded");

        }
        else if(result == JFileChooser.CANCEL_OPTION)
        {
            System.out.println("No File Selected");
        }
        
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //PatientDashboardJPanel pd = (PatientDashboardJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed
    
    private class ItemHandler implements ItemListener{
    
        @Override
        public void itemStateChanged(ItemEvent event){
            if(event.getSource() == complainTypeComboBox){
                governmentOrgComboBox.removeAllItems();
                for(Network network: business.getNetworkList()){
                    for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                        if(e instanceof DepartmentOfPublicHealthEnterprise){
                            for(Organization org:e.getOrganizationDirectory().getOrganizationList()){
//                                if(org instanceof DivisionOfInsurance && complainTypeComboBox.getSelectedItem().equals("Insurance Fraud"))
//                                    governmentOrgComboBox.addItem(org);
                                
                                if(org instanceof DivisionOfMedServices && complainTypeComboBox.getSelectedItem().equals("Medical Services Fraud"))
                                    governmentOrgComboBox.addItem(org);
                                
                                if(org instanceof DivisionOfAdulteration && complainTypeComboBox.getSelectedItem().equals("Adulteration Fraud"))
                                    governmentOrgComboBox.addItem(org);
                             }
                         
                        }
                    }
                }   
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea complainDescTextArea;
    private javax.swing.JTextField complainIdTextField;
    private javax.swing.JComboBox complainTypeComboBox;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JComboBox governmentOrgComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lodgeComplainBtn;
    private javax.swing.JTextField patientNameTextField;
    private javax.swing.JLabel pdfLabel;
    private javax.swing.JButton uploadButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

   
}
