/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital.Patient;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Hospital.PatientOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import UserInterface.Hospital.Patient.ComplainStatusJPanel;
import UserInterface.Hospital.Patient.LodgeComplainJPanel;
/**
 *
 * @author nikhi
 */
public class PatientDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientDashboardJPanel
     */
 private JPanel userProcessContainer;
  private Enterprise enterprise;
  private UserAccount userAccount;
  private PatientOrganization organization;
  //private ComplainWorkRequest request;
  private EcoSystem business;
  //private ReleaseOfInfoOrganization release;
   // private ReimbursementDirectory Reimbursedir;
    public PatientDashboardJPanel(JPanel userProcessContainer, UserAccount account, PatientOrganization patientOrganization, Enterprise enterprise, EcoSystem business) 
    {
          initComponents();
         this.userProcessContainer = userProcessContainer;
        this.organization = patientOrganization;
        this.enterprise = enterprise;
        this.userAccount = account;
        //this.business = new EcoSystem();
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DropDownLbl = new javax.swing.JLabel();
        workRequestsJButton = new javax.swing.JButton();
        complainJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 247, 247));

        DropDownLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DropDownLbl.setText("PATIENT WORK AREA");

        workRequestsJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        workRequestsJButton.setText("Check Work Request");
        workRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workRequestsJButtonActionPerformed(evt);
            }
        });

        complainJButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        complainJButton.setText("Raise a Complaint");
        complainJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainJButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samartha\\Desktop\\AED PROJECT IMAGES\\download.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(complainJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(workRequestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(DropDownLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(DropDownLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workRequestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complainJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void workRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workRequestsJButtonActionPerformed
        
        ComplainStatusJPanel complainstatusJPanel = new ComplainStatusJPanel(userProcessContainer,userAccount,enterprise ,organization, business);
        userProcessContainer.add("ComplainStatusJpanel", complainstatusJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_workRequestsJButtonActionPerformed

    private void complainJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainJButtonActionPerformed
        // TODO add your handling code here:
        LodgeComplainJPanel LodgeComplainJPanel = new LodgeComplainJPanel(userProcessContainer,userAccount,organization , enterprise,business);
        userProcessContainer.add("LodgeComplainJPanel", LodgeComplainJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_complainJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DropDownLbl;
    private javax.swing.JButton complainJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton workRequestsJButton;
    // End of variables declaration//GEN-END:variables
}
