/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FraudDetectionAgency.LawEnforcement;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DepartmentOfPublicHealth.DivisionOfInsurance;
import Business.Organization.FraudDetectionAgency.LawEnforcementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DepartmentToLawWorkRequest;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author nikhi
 */
public class BarChart_AnaylicsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private LawEnforcementOrganization lawEnforcementOrganization;
    private Enterprise enterprise;
    int medical_fraud_Count ;
    int insurance_fraud_Counter;
    int adulteration_fraud_counter;
    public BarChart_AnaylicsJPanel(String title,JPanel userProcessContainer, UserAccount account, LawEnforcementOrganization lawEnforcementOrganization , Enterprise enterprise) 
    {
       initComponents();
       this.userProcessContainer =  userProcessContainer;
       this.account = account;
       this.lawEnforcementOrganization = lawEnforcementOrganization;
       this.enterprise = enterprise;
       get_data();
       plot_chart();  
    }
        
    public void get_data()
    {
    for (DepartmentToLawWorkRequest DepartmenttolawWR : lawEnforcementOrganization.getWorkQueue().getDepartmenttolawWorkRequestList())
    {
        switch(DepartmenttolawWR.getComplainType())
                {
            case "Medical Services":
                  medical_fraud_Count++;
                break;
            case "Insurance Services":
                insurance_fraud_Counter++;
                break;
            case "Adulteration Fraud":
                adulteration_fraud_counter++;
                break;
            default:
                break;
        }  
    }
    }
        public void plot_chart()
        {
    DefaultCategoryDataset dataset =   new DefaultCategoryDataset( );
//    dataset.setValue(5,"Fraud" ,"Division of Insurance");
//    dataset.setValue(10,"Fraud" ,"Division of Adulteration");
//    dataset.setValue(20,"Fraud" ,"Division of Medical Services");
    dataset.setValue( insurance_fraud_Counter ,"Fraud" ,"Division of Insurance");
    dataset.setValue(adulteration_fraud_counter,"Fraud" ,"Division of Adulteration");
    dataset.setValue(medical_fraud_Count,"Fraud" ,"Division of Medical Services");
      
    JFreeChart jchart = ChartFactory.createBarChart("Fraud","Type of Fraud"," No of frauds ", dataset,PlotOrientation.VERTICAL,true,true,true);
    CategoryPlot plot =jchart.getCategoryPlot();
    plot.setRangeGridlinePaint(Color.black);
    
    ChartFrame chartframe = new ChartFrame("Fraud",jchart,true);
    chartframe.setVisible(true);
    chartframe.setSize(500,400);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
