/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FraudDetectionAgency.LawEnforcement;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FraudDetectionAgency.LawEnforcementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author mitka
 */
public class FirstLawEnforcementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FirstLawEnforcementJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem business;
    private Enterprise enterprise;
    private LawEnforcementOrganization lawEnforcementOrganization;
        
    public FirstLawEnforcementJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.business = business;
        this.lawEnforcementOrganization = (LawEnforcementOrganization) organization;
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workrequestButton = new javax.swing.JButton();
        analyticsButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 247, 247));

        workrequestButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        workrequestButton.setText("Check Work Requests");
        workrequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workrequestButtonActionPerformed(evt);
            }
        });

        analyticsButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        analyticsButton1.setText("Fraud History");
        analyticsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyticsButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samartha\\Desktop\\AED PROJECT IMAGES\\law.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(analyticsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(workrequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analyticsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workrequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void workrequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workrequestButtonActionPerformed
        LawEnforcementWorkRequestJPanel workrequestJPanel = new LawEnforcementWorkRequestJPanel(userProcessContainer,userAccount,lawEnforcementOrganization,enterprise,business);
        userProcessContainer.add("LawEnforcementWorkRequestJPanel", workrequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_workrequestButtonActionPerformed

    private void analyticsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyticsButton1ActionPerformed
        // TODO add your handling code here:
       String title = "Fraud";
        BarChart_AnaylicsJPanel BarChart_Anaylics = new BarChart_AnaylicsJPanel(title,userProcessContainer,userAccount,lawEnforcementOrganization,enterprise);
                userProcessContainer.add("BarChart_Anaylics",BarChart_Anaylics);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_analyticsButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyticsButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton workrequestButton;
    // End of variables declaration//GEN-END:variables
}
