/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FraudDetectionAgency.LawEnforcement;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FraudDetectionAgency.LawEnforcementOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DepartmentToLawWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mitka
 */
public class LawEnforcementWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LawyerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private Enterprise enterprise;
    private EcoSystem business;
    private LawEnforcementOrganization lawEnforcementOrganization;
    private DepartmentToLawWorkRequest request;
    
    public LawEnforcementWorkRequestJPanel(JPanel userProcessContainer,UserAccount useraccount, LawEnforcementOrganization lawEnforcementOrganization ,Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        this.business = business;
        this.lawEnforcementOrganization = lawEnforcementOrganization;
        enterpriseNameTextField.setText(enterprise.getName());
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) FraudComplainTable.getModel();
        
        model.setRowCount(0);       
        for(DepartmentToLawWorkRequest request:lawEnforcementOrganization.getWorkQueue().getDepartmenttolawWorkRequestList()){
            Object[]row = new Object[5];
            row[0] = request;
            row[1] = request.getMessage();
            row[2] = request.getSender();//getReq().getSender().getEmployee().getName();
            row[3] = request.getReceiver();//.getReq().getReceiver().getEmployee().getName();
            row[4] = request.getStatus();//getReq().getStatus();
            
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseNameTextField = new javax.swing.JTextField();
        refreshBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FraudComplainTable = new javax.swing.JTable();
        assignBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 247, 247));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("ENTERPRISE :");

        enterpriseNameTextField.setEditable(false);

        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        FraudComplainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Complain Type", "Message", "Sender", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(FraudComplainTable);

        assignBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        assignBtn.setText("Assign to me");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        processBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(enterpriseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(199, 199, 199)
                            .addComponent(refreshBtn))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(assignBtn)
                            .addGap(234, 234, 234)
                            .addComponent(processBtn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refreshBtn)
                    .addComponent(enterpriseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignBtn)
                    .addComponent(processBtn))
                .addContainerGap(210, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = FraudComplainTable.getSelectedRow();

        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row");
        }

        DepartmentToLawWorkRequest request = (DepartmentToLawWorkRequest)FraudComplainTable.getValueAt(selectedRow, 0);
        useraccount.getWorkQueue().getDepartmenttolawWorkRequestList().add(request);
        
        request.setReceiver(useraccount);
        //request.setReceiver(userAccount);
        //request.setStatus("Pending");
        populateTable();
    }//GEN-LAST:event_assignBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = FraudComplainTable.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        else{
            DepartmentToLawWorkRequest request = (DepartmentToLawWorkRequest) FraudComplainTable.getValueAt(selectedRow, 0);
            if(request.getReceiver()==null){
                JOptionPane.showMessageDialog(null, "Work request not assigned to anyone");
            }
            else{
                if(request.getStatus().equals("Completed")){
                    JOptionPane.showMessageDialog(null, "Request already processed");
                }
                else{
                request.setStatus("Processing");
                request.setOfficerName(useraccount.getUsername());
                ProcessFraudComplainJPanel processFraudComplainJPanel = new ProcessFraudComplainJPanel(userProcessContainer,request,business);
                userProcessContainer.add("ProcessFraudComplainJPanel",processFraudComplainJPanel);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                }
            }   
        }
    }//GEN-LAST:event_processBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FraudComplainTable;
    private javax.swing.JButton assignBtn;
    private javax.swing.JTextField enterpriseNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processBtn;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
