/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FraudDetectionAgency.LawEnforcement;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.Hospital.ReleaseOfInfoOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.ComplainWorkRequest;
import Business.WorkQueue.DepartmentToLawWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mitka
 */
public class ProcessFraudComplainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessFraudComplainJPanel
     */
    JPanel userProcessContainer;
    DepartmentToLawWorkRequest request;
    EcoSystem business;
    public ProcessFraudComplainJPanel(JPanel userProcessContainer,DepartmentToLawWorkRequest request,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.business = business;
  
        if(request.getComplainType().equals("Medical Services")){
            downloadButton.setEnabled(true);
            enterpriseNameTextField.setText(request.getReq().getEnterpriseName());
            complainTypeTextField.setText(request.getComplainType());
            fraudLevelTextField.setText(request.getFraudLevel());
            fraudReportPathTextField.setText(request.getFraudReportPath());
        }
        if(request.getComplainType().equals("Insurance Services")){
            enterpriseNameTextField.setText(request.getClaimReq().getHospEnterprise());
            complainTypeTextField.setText(request.getComplainType());
            fraudLevelTextField.setText(request.getFraudLevel());
            fraudReportPathTextField.setText(request.getFraudReportPath());
            downloadButton.setEnabled(false);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        penaltyTextField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        complainTypeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterpriseNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fraudLevelTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        downloadButton = new javax.swing.JButton();
        fraudReportPathTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(210, 247, 247));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Penalty Amount:");

        penaltyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penaltyTextFieldActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Complain Type:");

        complainTypeTextField.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Enterprise Name:");

        enterpriseNameTextField.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Fraud Level:");

        fraudLevelTextField.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Fraud Report:");

        downloadButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        downloadButton.setText("Download");
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        fraudReportPathTextField.setEditable(false);
        fraudReportPathTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fraudReportPathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fraudReportPathTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(complainTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(enterpriseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fraudLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(fraudReportPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(downloadButton))
                                    .addComponent(penaltyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(submitBtn)
                                .addGap(171, 171, 171)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(backBtn)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(enterpriseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(complainTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fraudLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(downloadButton)
                        .addComponent(fraudReportPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(penaltyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(submitBtn)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        backBtn();
    }//GEN-LAST:event_backBtnActionPerformed
    
    private void backBtn(){
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LawEnforcementWorkRequestJPanel dwjp = (LawEnforcementWorkRequestJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
    
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
//        request.setHospitalPenalty(Integer.parseInt(penaltyTextField.getText()));
        
        try{
//            int totalAmt = 0;
//            if(request.getPenaltyTotalAmount().containsKey(request.getReq().getEnterpriseName())){
//                totalAmt = request.getPenaltyTotalAmount().get(request.getReq().getEnterpriseName()) + Integer.parseInt(penaltyTextField.getText());
//                request.getPenaltyTotalAmount().put(request.getReq().getEnterpriseName(), totalAmt);
//            }
//            else{
//                totalAmt = Integer.parseInt(penaltyTextField.getText());
//                request.getPenaltyTotalAmount().put(request.getReq().getEnterpriseName(), totalAmt);
//            }
            if(request.getComplainType().equals("Medical Services")){
                request.setPenalty(Integer.parseInt(penaltyTextField.getText()));
                
                Organization org = null;
                for(Network network:business.getNetworkList()){
                    for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                        if(enterprise instanceof HospitalEnterprise && enterprise.getName().equals(request.getReq().getEnterpriseName())){
                            for(Organization looporg:enterprise.getOrganizationDirectory().getOrganizationList()){
                                if(looporg instanceof ReleaseOfInfoOrganization){
                                    org = looporg;
                                }
                            }
                        }
                    }
                }
                if(org!=null){
                    org.getWorkQueue().getDepartmenttolawWorkRequestList().add(request);
                    request.setStatus("Completed");
                    JOptionPane.showMessageDialog(null, "Penalty sent to the Enterprise");
                    
                    backBtn();
                }
            }
            else if(request.getComplainType().equals("Insurance Services")){
                request.setPenalty(Integer.parseInt(penaltyTextField.getText()));
                Organization org = null;
                for(Network network:business.getNetworkList()){
                    for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                        if(enterprise instanceof HospitalEnterprise && enterprise.getName().equals(request.getClaimReq().getHospEnterprise())){
                            for(Organization looporg:enterprise.getOrganizationDirectory().getOrganizationList()){
                                if(looporg instanceof ReleaseOfInfoOrganization){
                                    org = looporg;
                                }
                            }
                        }
                    }
                }
                if(org!=null){
                    org.getWorkQueue().getDepartmenttolawWorkRequestList().add(request);
                    request.setStatus("Completed");
                    JOptionPane.showMessageDialog(null, "Penalty sent to the Enterprise");
                    backBtn();
                }
            
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter valid inputs");
        }
        
    }//GEN-LAST:event_submitBtnActionPerformed

    private void penaltyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penaltyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penaltyTextFieldActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        // TODO add your handling code here:
        String paths = "\""+request.getFraudReportPath()+"\"";
        try{
                if(!paths.equals("\""+null+"\"")){
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+
                                      paths);
                fraudReportPathTextField.setText("File received");
                }
                else{
  
                    fraudReportPathTextField.setText("File not received");
                    
                }
        }
        catch(Exception e){
            fraudReportPathTextField.setText("File not received");
            
        }

    }//GEN-LAST:event_downloadButtonActionPerformed

    private void fraudReportPathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fraudReportPathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fraudReportPathTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField complainTypeTextField;
    private javax.swing.JButton downloadButton;
    private javax.swing.JTextField enterpriseNameTextField;
    private javax.swing.JTextField fraudLevelTextField;
    private javax.swing.JTextField fraudReportPathTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField penaltyTextField;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
