/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DepartmentOfPublicHealth.InsuranceOfficer;

import userinterface.HealthInsurance.ClaimsOrganization.*;
import userinterface.DepartmentOfPublicHealth.AdulterationOfficer.*;
import Business.EcoSystem;
import Business.Enterprise.DepartmentOfPublicHealthEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DepartmentOfPublicHealth.DivisionOfAdulteration;
import Business.Organization.DepartmentOfPublicHealth.DivisionOfInsurance;
import Business.Organization.HealthInsurance.ClaimsOrganization;
import Business.Organization.Organization;
import Business.Reimbursement;
import Business.ReimbursementDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Claim_DeptHealthInsuranceWorkRequest;
import Business.WorkQueue.ComplainWorkRequest;
import Business.WorkQueue.InsuranceWorkRequest;
import Business.WorkQueue.ROI_ClaimWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.Hospital.Releaseinfo.ClaimStatusJPanel;

/**
 *
 * @author mitka
 */
public class DivInsuranceOfficerWorkJPanel extends javax.swing.JPanel {

    private EcoSystem business;
    private UserAccount userAccount;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
   private String PatientId;
   private boolean flag;
   private String PatientMedicalId;
   private Claim_DeptHealthInsuranceWorkRequest Claim_DeptHealthWR;
   private DivisionOfInsurance divinsorg;
   private String PatientID;
   ClaimsOrganization claimsorg;
    /**
     * Creates new form AdulterationOfficerWorkAreaJPanel
     */
    public DivInsuranceOfficerWorkJPanel(JPanel userProcessContainer, UserAccount account,Enterprise enterprise, DivisionOfInsurance divorganization , EcoSystem business ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.business = business;
        this.Claim_DeptHealthWR = new Claim_DeptHealthInsuranceWorkRequest();
        this.divinsorg = divorganization;
        
        populateTable();
    }
    
    public void populateTable(){
        //get the Division of insurance data
        for(Network network: business.getNetworkList()){
            for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof DepartmentOfPublicHealthEnterprise){
                    for(Organization loopOrg:e.getOrganizationDirectory().getOrganizationList()){
                        if(loopOrg instanceof DivisionOfInsurance){
                            divinsorg =  (DivisionOfInsurance) loopOrg;
                            break;
                        }                      
                    }
                }
            }
        }
        
        DefaultTableModel model = (DefaultTableModel) StatusJTable.getModel();
        model.setRowCount(0);
        for(Claim_DeptHealthInsuranceWorkRequest request : divinsorg.getWorkQueue().getClaim_HealthInsuranceWorkRequest())
        {
            Object[]row = new Object[6];
            row[0] = request;
            row[1] = request.getPatientID();
            row[2] = request.getSender().getEmployee().getName();
            row[3] = request.getReceiver() == null ?null:request.getReceiver().getEmployee().getName();
            row[4] = request.getStatus();
            row[5] = request.getFraudDetected();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        assignBtn = new javax.swing.JButton();
        enterpriseNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        StatusJTable = new javax.swing.JTable();
        CheckContectBtn1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 247, 247));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("ENTERPRISE :");

        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        assignBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        assignBtn.setText("Assign to me");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        StatusJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "PatientID", "Sender", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StatusJTable);

        CheckContectBtn1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CheckContectBtn1.setText("Check the Content");
        CheckContectBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckContectBtn1ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(enterpriseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refreshBtn)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(CheckContectBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshBtn)
                    .addComponent(jButton7))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignBtn)
                    .addComponent(CheckContectBtn1))
                .addContainerGap(402, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = StatusJTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        Claim_DeptHealthWR = (Claim_DeptHealthInsuranceWorkRequest)StatusJTable.getValueAt(selectedRow, 0);
        Claim_DeptHealthWR.setReceiver(userAccount);
        Claim_DeptHealthWR.setStatus("Pending");
        populateTable();
    }//GEN-LAST:event_assignBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void CheckContectBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckContectBtn1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = StatusJTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        else
        {      
        Claim_DeptHealthWR = (Claim_DeptHealthInsuranceWorkRequest) StatusJTable.getValueAt(selectedRow, 0); 
        String PatientID = Claim_DeptHealthWR.getPatientID();
        ProcessInsuranceFraudJPanel ProcessInsuranceFraud = new ProcessInsuranceFraudJPanel(userProcessContainer,userAccount,divinsorg,PatientID,business,Claim_DeptHealthWR);
        userProcessContainer.add("ProcessInsuranceFraud", ProcessInsuranceFraud);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);  
        }      
    }//GEN-LAST:event_CheckContectBtn1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckContectBtn1;
    private javax.swing.JTable StatusJTable;
    private javax.swing.JButton assignBtn;
    private javax.swing.JTextField enterpriseNameTextField;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
